- hosts: aws
  become: True
  tasks:
    - name: installing python3
      apt:
        update_cache: yes
        pkg:
          - python3
          - python3-pip
          - python3.10-venv
        state: present

    - name: copying django project to server
      synchronize:
        src: Project/
        dest: /home/ubuntu

    - name: running script
      script: ./script.sh











    # - name: Install nginx
    #   apt:
    #     name: nginx
    #     state: present

    # - name: Create default index page
    #   copy:
    #     dest: /var/www/html/index.html
    #     content: "hello from abdelkhalek"

    # - name: Ensure the default nginx port is 8090
    #   replace:
    #    path: /etc/nginx/sites-enabled/default
    #    regexp: '80'
    #    replace: "8090"

    # - name: restart Nginx
    #   service: name=nginx state=restarted
    #   become: true
    #   become_method: sudo
    

